[package]
name = "jet"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]

[dependencies]
chrono = { version = "0.4.0", features = ["serde"] }
serde = "1.0.10"
serde_derive = "1.0.10"
reqwest = "0.7.1"
error-chain = "0.10.0"

[dev-dependencies]
dotenv = "0.10.1"